### PR TITLE
remove submodules; vendor with dep

### PR DESCRIPTION
**Pull request by jmank88**
My first attempt to install caire resulted in fatal git submodule errors, leaving me with a broken vendor directory. I fixed the problem by using [`dep`](https://github.com/golang/dep) instead.

This PR proposes using `dep` to vendor dependencies, and to remove submodules entirely. The `Gopkg.toml` was generated by `dep init` (I removed the example comment).

Committing the vendor directory is optional, but simpler and safer.

### CODE REVIEW

**Comment by esimov** [comment]
I have some uncertainty that this will integrate seamlessly with my homebrew installation. In fact i included the vendor dependencies because otherwise brew installation would broke. I will test with `go dep` and if will work i can accept this PR.

**Comment by jmank88** [comment]
I noticed you pushed an update using `glide`. I hope you'll still consider `dep` in the future, as that is `glide`'s own recommendation: https://github.com/Masterminds/glide#golang-dep

**Comment by esimov** [comment]
Thanks for the info, however at the moment i will stick with `glide`. Maybe in the feature i will consider to switch to `godep`.

**Comment by jmank88** [comment]
No problem.

Though just so there's no confusion, [godep](https://github.com/tools/godep) is a different tool (which also recommends [dep](https://github.com/golang/dep) in place of itself).

**Comment by esimov** [comment]
Uff, so many dependency managers :). Thanks.

**Pull request closed without merging**
