### PR TITLE
add support for piping with stdin and stdout (#43)

### LINKED ISSUE #43: Suggesting support for pipes
It would be ideal if pipes were usable with the CLI for enabling more expanded use-cases. After having [worked with ImageMagick](https://blog.alexellis.io/serverless-imagemagick/) in the past - I could see this being a highly requested feature.

With ImageMagick you can have the input arrive from a pipe, or have the output sent to a pipe.

Examples:

Pipe to file:

```
caire -in bridge.jpg -scale -perc 70 > small_bridge.jpg
```

Input from pipe:

```
caire -scale -perc 70 -out smaller_bridge.jpg < small_bridge.jpg
```

Input and output from pipe:

```
cat small_bridge.jpg | caire -scale -perc 70 > smaller_bridge.jpg
```

There are usages of pipes in the OpenFaaS CLI (also in Go) if that helps. https://github.com/openfaas/faas-cli

### PR DESCRIPTION
**Pull request by calebdoxsey**
Hi. This adds support for using stdin/stdout when the file name is `-`. This should fix #43.

### CODE REVIEW

**Comment by esimov** [comment]
Hey @calebdoxsey thanks for this amazing work. I will review it and if everything is ok I will merge it back to the master. I will let you know.

**Comment by esimov** [comment]
@calebdoxsey could you update the readme file with a few examples of how the library can be used with stdin/stdout pipes?

**Comment by calebdoxsey** [comment]
Thanks @esimov for the quick review. I've updated the readme with an example.

**Comment by calebdoxsey** [comment]
@esimov that makes sense. I updated the code to only show the message when not using stdout.

**Comment by esimov** [comment]
@calebdoxsey i've accepted your PR and merged it back to the master branch. A huge thanks for the work you have done.

**Pull request merged**
